### ISSUE TITLE
it is broken

### ISSUE THREAD

**Issue by Jab11n** [nojasm/fapture#1]
```
Error: ENOENT: no such file or directory, open 'C:\Users\jonas\Desktop\Projects\Websites\fapture\cache/bundles.json'
    at Object.writeFileSync (node:fs:2346:20)
    at BundleCache.save (/home/jabin/fapture/main.js:148:12)
    at new BundleCache (/home/jabin/fapture/main.js:143:18)
    at Object.<anonymous> (/home/jabin/fapture/main.js:429:19)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\jonas\\Desktop\\Projects\\Websites\\fapture\\cache/bundles.json'
}

Node.js v20.14.0
```
it tries to open a file from a windows computer (i am not jonas and i am on linux)

**Comment by nojasm** [comment]
It in fact was broken. User's config.json wasn't in gitignore yet
